# Generated by Django 4.2.5 on 2023-10-11 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.TextField()),
                ('parking_area_no', models.TextField(max_length=200)),
                ('vehicle_type', models.TextField(max_length=200)),
                ('vehicle_limit', models.TextField(max_length=200)),
                ('parking_charge', models.TextField(max_length=200)),
                ('status', models.TextField(max_length=200)),
                ('doc', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
