# Generated by Django 4.2.5 on 2023-10-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_dmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_id', models.TextField()),
                ('name', models.TextField(max_length=200)),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
    ]
