# Generated by Django 4.2.6 on 2023-10-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0005_alter_category_parking_area_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parking_area_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
