# Generated by Django 4.2.6 on 2023-10-16 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0006_alter_category_parking_area_no_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_in_parking_area', to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_with_charge', to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_of_type', to='pkapk.category'),
        ),
    ]
