# Generated by Django 4.2.6 on 2023-10-16 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0008_alter_add_vehicle_parking_area_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_area_vehicles', to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_vehicles', to='pkapk.category'),
        ),
    ]
