# Generated by Django 4.2.6 on 2023-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0026_alter_add_vehicle_parking_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.TextField(max_length=200),
        ),
    ]
