# Generated by Django 4.2.6 on 2023-10-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0029_alter_add_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='parking_area_no',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='parking_charge',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.ManyToManyField(related_name='vehicles_with_charge', to='pkapk.category'),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ManyToManyField(related_name='vehicle_type_vehicles', to='pkapk.category'),
        ),
    ]
