# Generated by Django 4.2.6 on 2023-10-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0030_rename_parking_area_no_add_vehicle_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_vehicle',
            old_name='category',
            new_name='parking_area_no',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='parking_charge',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
