# Generated by Django 4.2.6 on 2023-10-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0036_remove_add_vehicle_parking_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.CharField(default='Default Vehicle Type', max_length=200),
        ),
    ]
