# Generated by Django 4.2.6 on 2023-10-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0045_add_vehicle_parking_charge_add_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='parking_charge',
        ),
    ]
