# Generated by Django 4.2.6 on 2023-10-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0051_alter_add_vehicle_parking_area_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='a_dmin',
        ),
        migrations.RemoveField(
            model_name='add_vehicle',
            name='parking_charge',
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.CharField(max_length=200),
        ),
    ]
