# Generated by Django 4.2.6 on 2023-10-18 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0052_delete_a_dmin_remove_add_vehicle_parking_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_dmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('username', models.TextField(max_length=200)),
                ('password', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
