# Generated by Django 4.2.6 on 2023-10-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0057_add_vehicle_parking_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parking_area_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
