# Generated by Django 4.2.6 on 2023-10-18 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0059_remove_add_vehicle_parking_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.CharField(max_length=100),
        ),
    ]
