# Generated by Django 4.2.6 on 2023-10-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0065_add_vehicle_parking_area_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pkapk.category'),
        ),
    ]
