# Generated by Django 4.2.6 on 2023-10-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0073_alter_add_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='vehicle_type',
        ),
    ]
