# Generated by Django 4.2.6 on 2023-10-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0074_remove_add_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='vehicle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles_in_parking_area', to='pkapk.category'),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_area_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='parking_area_no',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='vehicle_type',
            field=models.CharField(max_length=200),
        ),
    ]
