# Generated by Django 4.2.6 on 2023-10-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0077_alter_add_vehicle_parking_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_vehicle',
            name='parking_charge',
        ),
    ]
