# Generated by Django 4.2.6 on 2023-10-19 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0078_remove_add_vehicle_parking_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.FloatField(default=0.0),
        ),
    ]
