# Generated by Django 4.2.6 on 2023-10-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0079_add_vehicle_parking_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_vehicle',
            name='parking_charge',
            field=models.CharField(max_length=200),
        ),
    ]
