# Generated by Django 4.2.6 on 2023-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0080_alter_add_vehicle_parking_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='vehicle_limit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
