# Generated by Django 4.2.6 on 2023-10-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkapk', '0082_alter_category_vehicle_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
